name: ci(ndk)

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

    - name: Setup NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26c

    - name: Build init
      run: ndk-build
