name: ci(with Android NDK)

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: jni

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26c

      - name: Build init
        run: cd jni && ndk-build
